content:
  - name: posts
    label: Posts
    path: src/_posts
    type: file
    fields: 
      - name: title
        label: Title
        type: string
      - name: fact
        label: Fact
        type: text
      - name: badge
        label: Is Classic Go-To
        type: boolean
    