content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    filename: '{primary}.md'
    view: 
      primary: title
    fields: 
      - name: title
        label: Title
        type: string
      - name: fact
        label: Fact
        type: text
      - name: badge
        label: Is Classic Go-To
        type: boolean
    